---
title: "Bootstrapping for sampling frequency PLATCOV"
author: "James Watson and Phrutsamon Wongnak"
format: pdf
editor: visual
---

```{r}
knitr::opts_chunk$set(cache = T, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)

```

```{r}
library(rstan)
library(tidyverse)
library(kableExtra)
library(finalfit)
library(RColorBrewer)
library(ggpubr)
library(grid)

## information on software/hardware used
version
sessionInfo()

rstan_options(auto_write = TRUE)
## parameters for the analysis
study_threshold = 1.2
RUN_MODELS = F

my_probs = c(0.025, 0.1, .5, .9, .975)
source('functions.R')
source("priors.R")
```

## Load data

Set up analysis

```{r}
mITT <- function(platcov_dat){
  platcov_dat = platcov_dat %>% group_by(ID) %>%
    mutate(
      mITT = any(Per_protocol_sample==1 & Timepoint_ID>=3) & !all(CT_NS==40))
  return(as.data.frame(platcov_dat))
}
```

```{r}
remdesivir_data = read.csv('Analysis_Data/Remdesivir_analysis.csv')
paxlovid_data = read.csv( 'Analysis_Data/Paxlovid_Molnupiravir_analysis.csv')
recent_paxlovid_data = read.csv('Analysis_Data/Paxlovid_recent_analysis.csv')
regeneron_data = read.csv('Analysis_Data/REGN_analysis.csv')

remdesivir_data <- mITT(remdesivir_data)
paxlovid_data <- mITT(paxlovid_data)
recent_paxlovid_data <- mITT(recent_paxlovid_data)
regeneron_data <- mITT(regeneron_data)

data_list <- list(remdesivir_data, paxlovid_data, recent_paxlovid_data, regeneron_data)
```

```{r}
for(i in 1:length(data_list)) {
  data_list[[i]]$VariantClass_new <-
    as.character(data_list[[i]]$Variant)
  data_list[[i]]$VariantClass_new[data_list[[i]]$VariantClass_new %in% c("BA.5.2", "BA.5.5", "BQ.1")] <-
    "BA.5"
  data_list[[i]]$VariantClass_new[data_list[[i]]$VariantClass_new %in% c("BN.1.2", "BN.1.3", "CH.1.1")] <-
    "BA.2.75"
  data_list[[i]]$VariantClass_new[data_list[[i]]$VariantClass_new %in% c("XBB1.5-like with F456L")] <-
    "XBB.1.5-like"
  
  data_list[[i]]$VariantClass_new <-
    as.factor(data_list[[i]]$VariantClass_new)
  
}


```

```{r}
interventions_all = c("Remdesivir", "Molnupiravir", "Regeneron", "Nirmatrelvir + Ritonavir", "Nirmatrelvir + Ritonavir", "Nirmatrelvir + Ritonavir")


ref_arms_all =  c("No study drug", "No study drug", "No study drug", "Molnupiravir", "No study drug", "No study drug")

data_ID <- c(1,2, 4, 2, 2, 3)

pairs <- paste(interventions_all,ref_arms_all, data_ID, sep = "_")
```

```{r}
Dmax_all <- 5 #c(2:7, 14)
day_plan <- c("0,1,2,3,4", "0,2,4", "0,4")
n_daily_swabs <- c(1,2)
bootstrap_rep = 50

pair_ID <- 1:6  

model_settings <-  expand.grid(mod = 'Stan_models/Linear_model_RNaseP.stan',
                               prior = 1,
                               cov_matrices = 1,
                               Dmax = Dmax_all,
                               day_plan = day_plan,
                               n_daily_swabs = n_daily_swabs,
                               pairs = pairs[pair_ID],
                               boot_rep = 1:bootstrap_rep)

model_settings <- model_settings %>%
  separate(pairs, c("intervention", "ref_arm", "data_ID"), "_")

model_settings$Niter = 4000
model_settings$Nwarmup = 2000
model_settings$Nthin = 8
model_settings$Nchain = 4

writeLines(sprintf('Numbers of posterior samples in total is %s',
                   unique((model_settings$Niter-model_settings$Nwarmup)*model_settings$Nchain/model_settings$Nthin)))

model_settings$data_ID <- as.numeric(model_settings$data_ID)
```

```{r}
model_setup_f_name = "Rout/model_settings_bootstraps_sampling_fq.RData"

save(model_settings, 
     data_list,
     all_priors,
     file = model_setup_f_name)
```

```{r}

if(RUN_MODELS){
  system(paste('Rscript --vanilla 03_run_local_bootstraps_analysis_sampling_fq.R'))
}
```

## Extract results

```{r}
res = array(dim = c(nrow(model_settings), 7))

for(i in 1:nrow(model_settings)){
   load(paste('Rout/03_Rout_bootstraps_analysis_sampling_fq/model_fits_bootstraps_fq',i,'.RData',sep=''))
  thetas_trt = rstan::extract(out, pars='trt_effect')$trt_effect
  res[i, ] = c(quantile(thetas_trt, probs = c(0.025, 0.5, 0.975)),
               quantile(thetas_trt, probs = 0.975)-
                 quantile(thetas_trt, probs = 0.025),
               sd(thetas_trt),
               mean(thetas_trt)/sd(thetas_trt),
               Rhat(matrix(thetas_trt, nrow = nrow(thetas_trt)/model_settings$Nchain[i], ncol = model_settings$Nchain[i]))
)
}
```

```{r}
colnames(res) <- c("low", "med", "up", "IC_width", "sd", "z_score", "Rhat")

results <- cbind(model_settings, res)
results$contrasts <- paste0(results$intervention, results$ref_arm, results$data_ID)

results$day_plan <- as.factor(results$day_plan)
levels(results$day_plan) <- c("5 days", "3 days", "2 days")

results$n_daily_swabs <- as.factor(results$n_daily_swabs)
levels(results$n_daily_swabs) <- c("1 swab/day", "2 swabs/day")

unique_contrast <- unique(results$contrasts)

results <- results[results$Rhat < 1.015,]
```

```{r}
results_median <- results %>%
  group_by(contrasts, day_plan, n_daily_swabs) %>%
  summarise(med_z = median(z_score),
            low_z = quantile(z_score, 0.025),
            up_z = quantile(z_score, 0.975)) %>%
  as.data.frame()
```

## Plot

```{r}
tags <- c("A", "B", "C", "D", "E", "F")

plot_list <- list()

for(i in 1:length(unique_contrast)){
  data_plot_all <- results[results$contrasts == unique_contrast[i], ]
  data_plot_median <- results_median[results_median$contrasts == unique_contrast[i], ]
  
   intervention <- data_plot_all$intervention[1]
   ref_arm <- data_plot_all$ref_arm[1]
   
   data_ID <- data_plot_all$data_ID[1]

   if(intervention == "Nirmatrelvir + Ritonavir"){intervention <- "Nirmatrelvir"}
   if(intervention == "Regeneron"){intervention <- "Casirivimab/imdevimab"}
  
   if(intervention == "Nirmatrelvir" & data_plot_all$data_ID[1] == 2 &
      ref_arm == "No study drug"){ref_arm <- "No study drug (before Feb 2023)"}
   if(intervention == "Nirmatrelvir" & data_plot_all$data_ID[1] == 3){ref_arm <- "No study drug (after Feb 2023)"}

  
   lab <- paste0(intervention, " vs \n", ref_arm)
  
   tag <- tags[i]
  
  plot_list[[i]] <-
  
ggplot() +
  geom_boxplot(data = data_plot_all, aes(x = day_plan, y = z_score, fill = n_daily_swabs), 
               position  = position_dodge(width = 0.65),
               width = 0.5, alpha = 0.75, linewidth = 0.55,
               color = "#424769") +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.55) +
  theme_bw() +
  scale_y_continuous(breaks = seq(-2,10,2), limits = c(-2,10)) +
  scale_fill_manual(values = c("#FF004D", "#525CEB"), name = "") +
  xlab("") +
  ylab("") +
  ggtitle(lab) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 9),
        axis.text = element_text(size = 8),
        plot.tag.position = c(0.175,0.99),
        plot.tag = element_text(size = 9, face = "bold")) +
  labs(tag = tag)
  
}

G <- ggarrange(plotlist = plot_list, ncol = 3, nrow = 2, common.legend = T, legend = "right") 
G
```

```{r}
png("Plots/z_scores_sampling_fq.png", width = 10, height = 6.5, units = "in", res = 350)
annotate_figure(G, left = textGrob("Z-score", rot = 90, vjust = 0.5, gp = gpar(cex = 1.2, fontface="bold")),
                bottom = textGrob("Sampling schedule", gp = gpar(cex = 1.2, fontface="bold")))
dev.off()
```
