---
title: "Temporal changes in viral load kinetics"
author: "Phrutsamon Wongnak & James Watson"
format: html
editor: visual
---

```{r preambule}
knitr::opts_chunk$set(cache = F, cache.comments = FALSE,
                      echo = F, include = TRUE, 
                      fig.width = 8, fig.height = 8,
                      fig.pos = 'H',dev = 'png', dpi = 300)

```

```{r setup}
library(rstan)
library(tidyverse)
library(kableExtra)
library(finalfit)
library(RColorBrewer)
library(lubridate)
library(lme4)
library(survival)
library(survminer)
library(gridExtra)
library(brms)

## information on software/hardware used
version
sessionInfo()

rstan_options(auto_write = TRUE)
## parameters for the analysis
Dmax = 5.5
RUN_MODELS = F
add_epoch = T # if using non-concurrent controls

my_probs = c(0.025, 0.1, .5, .9, .975)
source('functions.R')
trt_colors = get_trt_colors()
```

## *Load data*

*Set up analysis*

```{r load_data}
intervention = 'interim_all' # prefix of analysis file
ref_arm = 'No study drug'
study_threshold = 1.2 # depending on comparison with no study drug or positive control
```

```{r define_population}
#| echo: false
# set as file with relevant dataset
itt_population_all = get_itt_population()

f_name = paste0('Analysis_Data/',intervention,'_analysis.csv')
platcov_dat = read.csv(f_name)
platcov_dat <- platcov_dat %>% filter(Trt %in% c("No study drug", 
                                                 "Ivermectin",
                                                 "Regeneron",
                                                 "Remdesivir",
                                                 "Favipiravir", 
                                                 "Molnupiravir", 
                                                 "Nirmatrelvir + Ritonavir"))

platcov_dat$Trt[platcov_dat$Trt=='Nirmatrelvir + Ritonavir']='Nirmatrelvir'

platcov_dat$Rand_date = as.POSIXct(platcov_dat$Rand_date)
trt_intervention = unique(platcov_dat$Trt)

# interventions
if(length(trt_intervention)==0) stop('no interventions!')
trts = trt_intervention[trt_intervention!=ref_arm] # get interventions
```

## *Make modified intention to treat population*

```{r make_analysis_data}
#| echo: false
platcov_dat = platcov_dat %>% group_by(ID) %>%
  mutate(
    mITT = any(Per_protocol_sample==1 & Timepoint_ID>=3) &
      (sum(CT_NS<40)>2))

pop_table = platcov_dat %>% distinct(ID, .keep_all = T)
table(Intervention=pop_table$Trt, `mITT population` = pop_table$mITT)
```

## *Baseline characteristics*

```{r}
#| echo: false
platcov_dat = platcov_dat %>% group_by(ID, Timepoint_ID) %>%
  mutate(daily_VL = mean(log10_viral_load),
         daily_censor = all(censor=='left')) %>% 
  ungroup() %>%
  mutate(Sex = as.factor(ifelse(Sex==1,'Male','Female')),
         Site = as.factor(Site),
         Trt = factor(Trt, levels=c(ref_arm, trts)),
         Vaccinated = as.factor(ifelse(N_dose>0,'Yes','No')),
         Variant = as.factor(Variant),
         Time_since_last_dose = ifelse(is.na(Time_since_last_dose)&Vaccinated=='No',
                                       600,Time_since_last_dose),
         trt_color = 
           as.character(plyr::mapvalues(Trt,
                                        from = names(trt_colors),
                                        to = trt_colors)),
         Study_time = as.numeric(difftime(Rand_date,min(Rand_date),units = 'weeks')),
         Study_time = scale(Study_time) #normalise
  )

Baseline_data = platcov_dat %>% ungroup() %>% 
  distinct(ID, .keep_all = T) %>%
  filter(Timepoint_ID==0) %>% 
  mutate(Baseline.viral.load = daily_VL)


tab.ff <- Baseline_data %>% filter(mITT) %>%
  summary_factorlist(
    dependent = "Trt", # name of grouping / treatment variable
    explanatory = c("Site", "Age", 'BMI', "Weight",
                    "Baseline.viral.load",'Sex','Fever_Baseline',
                    "Variant",'Symptom_onset','Vaccinated'),
    total_col = F, # add column with statistics for the whole sample
    add_row_total = F, # add column with number of valid cases
    include_row_missing_col = FALSE,
    add_dependent_label = T,
    na_include = TRUE # make variables' missing data explicit
  ) 

df <- knitr::kable(tab.ff, format = 'latex')
writeLines(df, 'df.tex')

tab.ff = tab.ff%>%
  kbl(
    caption = NULL,
    booktabs = TRUE,
    align = "lrlrrr",
  ) %>%
  kable_classic(full_width = FALSE)
tab.ff
```

Some simple models for the baseline viral load. Which covariates best predict a high baseline viral load?

```{r baseline_VL_temporal_trend}
baseline_VL_time = ggplot(data=Baseline_data,
                          aes(x=Rand_date,
                              y=Baseline.viral.load, col=Variant)) +
  geom_point() + 
  labs(x = "Randomisation date", y = 'Viral load at enrolment')+
  scale_y_continuous(breaks = 1:9,
                     labels = function(x) sprintf("10^%d", x))+
  theme_minimal(base_size = 18)+
  geom_smooth(method = mgcv::gam, formula = y~s(x),
              se = T, color = "black", aes(group = 1))
# guides(col = 'none')
baseline_VL_time
mod_baseline = lm(Baseline.viral.load~BMI+Age+Sex+Symptom_onset+Vaccinated+Variant+Site+Fever_Baseline,
                  data = Baseline_data)
summary(mod_baseline)
```

### Rate of clearance over time

```{r}
# Analysis data
platcov_dat_analysis = 
  platcov_dat %>% ungroup() %>%
  filter(Time <= Dmax, mITT, Timepoint_ID < ceiling(Dmax)) %>%
  arrange(log10_viral_load==log10_cens_vl) %>%
  mutate(Variant = as.factor(Variant),
         Site = as.factor(Site),
         RnaseP_scaled = scale(40 - CT_RNaseP,scale = F),
         Mean_age = mean(Age[!duplicated(ID)]),
         SD_age = sd(Age[!duplicated(ID)]),
         Age_scaled = (Age-Mean_age)/SD_age,
         Symptom_onset = ifelse(is.na(Symptom_onset),2,Symptom_onset)) 
```

```{r }
if(RUN_MODELS){
  
  my_form = bf(log10_viral_load|cens(censor) ~ Time*Trt+Site+RnaseP_scaled+(1+Time|ID))
  get_prior(formula = my_form,data = platcov_dat_analysis,family = 'student')
  mod_naive = brm(formula = my_form,
                  data = platcov_dat_analysis,
                  prior = c(prior(lkj(2), class = "cor"),
                            prior(normal(5, 5), class = Intercept),
                            prior(normal(0, 1), class='b'),
                            prior(constant(7), class = 'nu')),
                  family = 'student', cores = 4, chains = 4)
  save(mod_naive, file = 'Rout/brms_fit.RData')
} else {
  load('Rout/brms_fit.RData')
}
my_preds = apply(posterior_predict(mod_naive), 2, quantile)
```

```{r slopes_time, fig.width=8, fig.height=8}
slopes_dat = platcov_dat_analysis %>% distinct(ID,.keep_all = T) %>%
  arrange(Rand_date)
slopes_dat$slope=NA
for(i in 1:nrow(slopes_dat)){
  ind = which(platcov_dat_analysis$ID==slopes_dat$ID[i])
  slopes_dat$slope[i] = coef(lm(my_preds[3,ind]~platcov_dat_analysis$Time[ind]))[2]
}
mod_gam_NSD = mgcv::gam(slope ~ s(Study_time,k=4), data=slopes_dat%>%filter(Trt=='No study drug'))

par(las=1, family='serif',cex.lab=1.3, cex.axis=1.3, mfrow=c(3,2))
for(my_trt in list(t1='No study drug', 
                   t2='Nirmatrelvir',
                   t3=c('Remdesivir','Molnupiravir'),
                   t4='Favipiravir',
                   t5='Ivermectin',
                   t6='Regeneron')){
  
  slopes_my_trt = slopes_dat %>% filter(Trt %in% my_trt)
  slopes_my_trt$Var = as.factor(as.character(slopes_my_trt$Variant))
  plot(slopes_my_trt$Rand_date, slopes_my_trt$slope,
       ylab='Viral reduction per day (log10 units)',
       ylim=range(slopes_dat$slope),
       col=adjustcolor(slopes_my_trt$trt_color,.5),
       xlim = range(slopes_dat$Rand_date),
       xlab='Randomisation date', panel.first=grid(), 
       pch=15)#+as.numeric(slopes_my_trt$Var))
  abline(h=0)
  
  my_leg = paste(unique(slopes_my_trt$Trt),
                 'n=',table(as.character(slopes_my_trt$Trt)))
  legend('bottomleft',legend = my_leg,
         col = unique(slopes_my_trt$trt_color),
         pch=16,lwd=2,inset=0.02)
  
  for(tt in my_trt){
    dat = slopes_my_trt %>% filter(Trt==tt)
    
    writeLines(sprintf('******* Doing trt %s', tt))
    mods=list(); xs = list()
    if(tt == 'Regeneron'){
      dat$Subgroup = as.character(dat$Variant)
      dat$Subgroup = ifelse(dat$Variant=='BA.1' | 
                              dat$Variant=='BA.2.75',
                            'Omicron G446S mutated', dat$Subgroup)
      dat$Subgroup = ifelse(dat$Variant!='Delta' & 
                              dat$Subgroup!='Omicron G446S mutated',
                            'Omicron not G446S mutated', dat$Subgroup)
      
      for(ss in 1:length(unique(dat$Subgroup))){
        dat_ss = dat%>%filter(Subgroup==unique(dat$Subgroup)[ss])
        mods[[ss]] = 
          lm(slope ~ Study_time,data=dat_ss)
        xs[[ss]] = dat_ss$Rand_date
      }
    } else {
      mods = list(mod1=lm(slope ~ Study_time, data=dat))
      xs = list(date=dat$Rand_date)
      print(summary(mods[[1]]))
    }
    
    if('No study drug' != tt) {
      for(i in 1:length(mods))
        lines(xs[[i]], predict(mods[[i]]),lwd=3,
              col=dat$trt_color)
    }
  }
  
  lines(slopes_dat$Rand_date[slopes_dat$Trt=='No study drug'],
        predict(mod_gam_NSD),lwd=3,lty=2,
        col=(slopes_dat$trt_color[slopes_dat$Trt=='No study drug']))
  
}

writeLines(sprintf('Viral clearance half-lives in the no study drug arm have gone from %s hours to %s hours',
                   round(-24*log10(2)/predict(mod_gam_NSD)[1]),
                   round(-24*log10(2)/last(predict(mod_gam_NSD)))))
```
